let data = {
    "Get current page URL window.location.href is a JavaScript statement that retrieves the current URL of the web page in the browser and assigns it to the href property of the location object. It does not require any HTML tags to function.": {
        "tag": "Get current page URL",
        "code": "window.location.href",
        "desc": "window.location.href is a JavaScript statement that retrieves the current URL of the web page in the browser and assigns it to the href property of the location object. It does not require any HTML tags to function."
    },
    "Redirect to URLThis code changes the current page's URL to the specified \"path\". It doesn't affect any HTML tags directly, but it could trigger a new page to be loaded if the specified path is a valid URL.": {
        "tag": "Redirect to URL",
        "code": "window.location.href = \"path\"",
        "desc": "This code changes the current page's URL to the specified \"path\". It doesn't affect any HTML tags directly, but it could trigger a new page to be loaded if the specified path is a valid URL."
    },
    "Assign multiple CSS properties to an elementThis code sets the CSS styles of an element to the specified values. It allows you to apply multiple CSS properties and their values to an element's inline style attribute at once.": {
        "tag": "Assign multiple CSS properties to an element",
        "code": "element.style.cssText = 'property1:value;property2:value;.....propertyN:value;'",
        "desc": "This code sets the CSS styles of an element to the specified values. It allows you to apply multiple CSS properties and their values to an element's inline style attribute at once."
    },
    "Completely change inner HTML of an elementThis code replaces the content of an HTML element with the specified HTML code. It allows you to change the text, images, and other HTML elements inside an element dynamically.": {
        "tag": "Completely change inner HTML of an element",
        "code": "element.innerHTML = \"new html\"",
        "desc": "This code replaces the content of an HTML element with the specified HTML code. It allows you to change the text, images, and other HTML elements inside an element dynamically."
    },
    "Prevent form submissionThis code  prevents the default action of a form submission. It allows you to handle the form data without actually submitting the form to the server.": {
        "tag": "Prevent form submission",
        "code": "formElement.addEventListener('submit', function (e) {\n    e.preventDefault();\n});",
        "desc": "This code  prevents the default action of a form submission. It allows you to handle the form data without actually submitting the form to the server."
    },
    "Set focus on an elementThis code sets the focus to an HTML element, meaning that it selects the element and makes it ready to accept user input. It is often used to bring user attention to a specific element on a web page, such as a form input field.": {
        "tag": "Set focus on an element",
        "code": "element.focus();",
        "desc": "This code sets the focus to an HTML element, meaning that it selects the element and makes it ready to accept user input. It is often used to bring user attention to a specific element on a web page, such as a form input field."
    },
    "Access label of an input fieldThis code returns the first <label> element associated with an <input> element. This can be useful for getting information about the label, such as its text content or its for attribute.": {
        "tag": "Access label of an input field",
        "code": "input_element.labels[0]",
        "desc": "This code returns the first <label> element associated with an <input> element. This can be useful for getting information about the label, such as its text content or its for attribute."
    },
    "Scroll to an elementThis code scrolls the window to a specific position, with a smooth animation.": {
        "tag": "Scroll to an element",
        "code": "window.scrollTo({\n    top: value,\n    behavior: \"smooth\",\n    left: value\n});",
        "desc": "This code scrolls the window to a specific position, with a smooth animation."
    },
    "Get HTML from a URLThis code sends an HTTP request to a server using the XMLHttpRequest object, retrieves the response data as a string, creates a new HTML \"div\" element and sets its innerHTML to the response data. Then, it selects an element inside the \"div\" element using a CSS selector but does not do anything further with it.": {
        "tag": "Get HTML from a URL",
        "code": "let xhr = new XMLHttpRequest();\nlet html = xhr.responseTxt;\nlet ele = document.createElement(\"div\");\nele.innerHTML = html;\nele.querySelector(\"selector of element inside of ele\")",
        "desc": "This code sends an HTTP request to a server using the XMLHttpRequest object, retrieves the response data as a string, creates a new HTML \"div\" element and sets its innerHTML to the response data. Then, it selects an element inside the \"div\" element using a CSS selector but does not do anything further with it."
    },
    "Detect page bottomThe code adds an event listener to the window object that listens for the \"scroll\" event. When the user scrolls the page, the code checks if the vertical distance from the top of the page to the bottom of the viewport plus 25 pixels is greater than or equal to the height of the entire document body. If it is, the code logs a message to the console.": {
        "tag": "Detect page bottom",
        "code": "window.addEventListener(\"scroll\", (e) => {\n    if (window.scrollY + window.innerHeight + 25 >= document.body.offsetHeight) {\n        console.log(\"Hurray, we are at the bottom of the page!!! :)\");\n    }\n});",
        "desc": "The code adds an event listener to the window object that listens for the \"scroll\" event. When the user scrolls the page, the code checks if the vertical distance from the top of the page to the bottom of the viewport plus 25 pixels is greater than or equal to the height of the entire document body. If it is, the code logs a message to the console."
    },
    "Scroll to an element without positionThis code scrolls the viewport to bring the specified \"element\" into view, using a smooth scrolling animation rather than an instant jump. The \"behavior: smooth\" option is passed as an object to the \"scrollIntoView\" method to achieve this smooth scrolling effect.": {
        "tag": "Scroll to an element without position",
        "code": "element.scrollIntoView({\n    behavior: \"smooth\"\n});",
        "desc": "This code scrolls the viewport to bring the specified \"element\" into view, using a smooth scrolling animation rather than an instant jump. The \"behavior: smooth\" option is passed as an object to the \"scrollIntoView\" method to achieve this smooth scrolling effect."
    },
    "Decode URLthis code decodes the URL of the current web page, which is stored in the \"window.location.href\" property, and assigns the decoded URL to the variable \"decodedURL\". The \"decodeURIComponent\" function is used to decode any special characters in the URL, such as \"%20\" for a space character. If there are any errors during the decoding process, the code logs an error message to the console.": {
        "tag": "Decode URL",
        "code": "let decodedURL;\ntry {\n    decodedURL = decodeURIComponent(window.location.href);\n} catch (e) {\n    console.error(\"Error decoding URL: \" + e.message);\n}",
        "desc": "this code decodes the URL of the current web page, which is stored in the \"window.location.href\" property, and assigns the decoded URL to the variable \"decodedURL\". The \"decodeURIComponent\" function is used to decode any special characters in the URL, such as \"%20\" for a space character. If there are any errors during the decoding process, the code logs an error message to the console."
    },
    "Search element based on the text inside of itThis code selects all the elements in the document that match the given CSS selector, and filters them to return only those elements whose text content matches the given \"text\" parameter. The text comparison is done after removing any non-alphanumeric characters and extra whitespace, and after converting both the element's text content and the search text to uppercase. The function returns an array of elements that match the search text.": {
        "tag": "Search element based on the text inside of it",
        "code": "function contains(selector, text) {\n    var elements = document.querySelectorAll(selector);\n    return [].filter.call(elements, function (element) {\n        return text.replace(/[^\\w\\s]/gi, '').replace(/\\s+/g, ' ').toUpperCase() === element.innerText.replace(/[^\\w\\s]/gi, '').replace(/\\s+/g, ' ').toUpperCase();\n    });\n}",
        "desc": "This code selects all the elements in the document that match the given CSS selector, and filters them to return only those elements whose text content matches the given \"text\" parameter. The text comparison is done after removing any non-alphanumeric characters and extra whitespace, and after converting both the element's text content and the search text to uppercase. The function returns an array of elements that match the search text."
    },
    "Extract search queryThis code creates a new \"URLSearchParams\" object to extract and parse the query parameters from the URL of the current page. The \"entries\" method is used to iterate over all the query parameter key-value pairs in the object. For each pair, a new key-value pair is added to the \"searchQuery\" object, with the same key and value as in the URL parameters. The result is a JavaScript object that represents the search query parameters from the current URL, which can be used to access and manipulate the query parameters programmatically.": {
        "tag": "Extract search query",
        "code": "let searchParams = new URLSearchParams(window.location.search);\nlet searchQuery = {};\nfor (const [key, value] of searchParams.entries()) {\n    searchQuery[key] = value;\n}",
        "desc": "This code creates a new \"URLSearchParams\" object to extract and parse the query parameters from the URL of the current page. The \"entries\" method is used to iterate over all the query parameter key-value pairs in the object. For each pair, a new key-value pair is added to the \"searchQuery\" object, with the same key and value as in the URL parameters. The result is a JavaScript object that represents the search query parameters from the current URL, which can be used to access and manipulate the query parameters programmatically."
    },
    "Get cookieThis code defines a JavaScript function called \"getCookie\" that takes a cookie name as a parameter and returns the corresponding cookie value. The function first constructs a string that consists of the cookie name followed by an equal sign (e.g. \"cookieName=\"). It then splits the \"document.cookie\" string into individual cookies by splitting on semicolons, and iterates over each cookie to find the one that matches the provided cookie name. If the cookie is found, the function returns its value, which is everything after the equal sign. If the cookie is not found, the function returns null.": {
        "tag": "Get cookie",
        "code": "var getCookie = function (name) {\n    var nameEQ = name + '=';\n    var ca = document.cookie.split(';');\n    for (var i = 0; i < ca.length; i++) {\n        var c = ca[i];\n        while (c.charAt(0) == ' ') c = c.substring(1, c.length);\n        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);\n    }\n    return null;\n};",
        "desc": "This code defines a JavaScript function called \"getCookie\" that takes a cookie name as a parameter and returns the corresponding cookie value. The function first constructs a string that consists of the cookie name followed by an equal sign (e.g. \"cookieName=\"). It then splits the \"document.cookie\" string into individual cookies by splitting on semicolons, and iterates over each cookie to find the one that matches the provided cookie name. If the cookie is found, the function returns its value, which is everything after the equal sign. If the cookie is not found, the function returns null."
    },
    "Set cookiethis code defines a JavaScript function called \"setCookie\" that takes a cookie name, a cookie value, and an optional number of days as parameters. The function first checks if a number of days was provided, and if so, it creates a new Date object and sets the expiration time to the current time plus the number of days provided (in milliseconds). It then constructs a string that consists of the cookie name, value, and expiration time, separated by semicolons and spaces. Finally, it sets the \"document.cookie\" property to this string, which adds the cookie to the browser's cookie storage. The cookie is set for the current path (i.e. \"/\", which means it applies to all pages on the current domain).": {
        "tag": "Set cookie",
        "code": "var setCookie = function (name, value, days) {\n    var expires = '';\n    if (days) {\n        var date = new Date();\n        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));\n        expires = '; expires=' + date.toUTCString();\n    }\n    document.cookie = name + '=' + value + expires + '; path=/';\n};",
        "desc": "this code defines a JavaScript function called \"setCookie\" that takes a cookie name, a cookie value, and an optional number of days as parameters. The function first checks if a number of days was provided, and if so, it creates a new Date object and sets the expiration time to the current time plus the number of days provided (in milliseconds). It then constructs a string that consists of the cookie name, value, and expiration time, separated by semicolons and spaces. Finally, it sets the \"document.cookie\" property to this string, which adds the cookie to the browser's cookie storage. The cookie is set for the current path (i.e. \"/\", which means it applies to all pages on the current domain)."
    },
    "Count Down TimerThis code defines a function named timer which takes two arguments: timerObj and endDateString.\n\nThe function sets up a timer interval that updates the countdown displayed on a web page, based on the difference between the current date and the endDate passed as a string in endDateString.\n\nThe timer is cleared and a DOM element is removed if the current date exceeds the endDate.\n\nThe countdown displays the number of days, hours, minutes and seconds left until the endDate, with leading zeros added to numbers less than 10.\n": {
        "tag": "Count Down Timer",
        "code": "function timer(timerObj, endDateString) {\n    const endDate = new Date(endDateString);\n  \n    timerInterval = setInterval(() => {\n      const currentDate = new Date();\n      if (currentDate >= endDate) {\n        clearInterval(timerInterval);\n        // removing timer if it meets the future date\n        document.querySelector(\"element_selector\").remove();\n        return;\n      }\n      \n      // convert the end date to UTC\n      const utcEndDate = new Date(\n        Date.UTC(\n          endDate.getUTCFullYear(),\n          endDate.getUTCMonth(),\n          endDate.getUTCDate(),\n          endDate.getUTCHours(),\n          endDate.getUTCMinutes(),\n          endDate.getUTCSeconds()\n        )\n      );\n  \n      // calculate time remaining\n      const diff = utcEndDate - currentDate;\n      const daysLeft = Math.floor(diff / (1000 * 60 * 60 * 24));\n      let hoursLeft = Math.floor((diff % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));\n      let minsLeft = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));\n      let secsLeft = Math.floor((diff % (1000 * 60)) / 1000);\n  \n      // update the timer values\n      timerObj.dys.textContent = (daysLeft <= 0) ? \"0\" : (daysLeft < 10) ? `0${daysLeft}` : daysLeft;\n      timerObj.hours.textContent = (hoursLeft <= 0) ? \"0\" : (hoursLeft < 10) ? `0${hoursLeft}` : hoursLeft;\n      timerObj.mins.textContent = (minsLeft <= 0) ? \"0\" : (minsLeft < 10) ? `0${minsLeft}` : minsLeft;\n      timerObj.secs.textContent = (secsLeft <= 0) ? \"0\" : (secsLeft < 10) ? `0${secsLeft}` : secsLeft;\n  \n    }, 1000);\n  }",
        "desc": "This code defines a function named timer which takes two arguments: timerObj and endDateString.\n\nThe function sets up a timer interval that updates the countdown displayed on a web page, based on the difference between the current date and the endDate passed as a string in endDateString.\n\nThe timer is cleared and a DOM element is removed if the current date exceeds the endDate.\n\nThe countdown displays the number of days, hours, minutes and seconds left until the endDate, with leading zeros added to numbers less than 10.\n"
    },
    "YOUTUBE THUMBNAIL FETCHThis code defines three variables that contain URLs to different thumbnail images for a YouTube video.\n\nThe first variable default contains the URL for the default quality thumbnail image of a YouTube video. The second variable hd contains the URL for the high-definition quality thumbnail image of a YouTube video. The third variable mobileFriendly contains the URL for the mobile-friendly quality thumbnail image of a YouTube video.\n\nThese URLs can be used to display thumbnail images for a YouTube video on a website or application.": {
        "tag": "YOUTUBE THUMBNAIL FETCH",
        "code": "let default = 'https://img.youtube.com/vi/<insert-youtube-video-id-here>/default.jpg'\nlet hd = 'https://img.youtube.com/vi/DOyWP3GPWJ8/maxresdefault.jpg'\nlet mobileFriendly = 'https://img.youtube.com/vi/DOyWP3GPWJ8/mqdefault.jpg'",
        "desc": "This code defines three variables that contain URLs to different thumbnail images for a YouTube video.\n\nThe first variable default contains the URL for the default quality thumbnail image of a YouTube video. The second variable hd contains the URL for the high-definition quality thumbnail image of a YouTube video. The third variable mobileFriendly contains the URL for the mobile-friendly quality thumbnail image of a YouTube video.\n\nThese URLs can be used to display thumbnail images for a YouTube video on a website or application."
    },
    "This function traverses up the DOM from a given element to find the closest parent element with a specified class.This code defines a function called closestByClass that takes two parameters: an element (el) and a class name (clazz). The function traverses the DOM (Document Object Model) up from the given element until it finds an ancestor element that has the specified class. If no ancestor element has the specified class, the function returns null. Once an ancestor element with the specified class is found, the function returns that element.\n\nIn other words, this function returns the closest ancestor element of the given element that has the specified class name.": {
        "tag": "This function traverses up the DOM from a given element to find the closest parent element with a specified class.",
        "code": "var closestByClass = function (el, clazz) {\n    // Traverse the DOM up with a while loop\n    while (!el.classList.contains(clazz)) {\n        // Increment the loop to the parent node\n        el = el.parentNode\n        if (!el) {\n            return null\n        }\n    }\n\n    // At this point, the while loop has stopped and `el` represents the element\n    // that has the class you specified in the second parameter of the function\n    // `clazz`\n    return el\n}",
        "desc": "This code defines a function called closestByClass that takes two parameters: an element (el) and a class name (clazz). The function traverses the DOM (Document Object Model) up from the given element until it finds an ancestor element that has the specified class. If no ancestor element has the specified class, the function returns null. Once an ancestor element with the specified class is found, the function returns that element.\n\nIn other words, this function returns the closest ancestor element of the given element that has the specified class name."
    },
    "Javascript autocomplete This code defines an array of objects that contain information about various products, including a name, link, and a keyword that describes the product. It also includes a function called showList() which listens for user input in a search box and filters the products based on whether their associated keyword matches the search query. It then dynamically generates HTML elements to display a list of the filtered products as clickable links.\nThis code adds an event listener to an input field that filters through an array of products and displays matching items in a suggestion list. The suggestion list is updated dynamically as the user types into the input field.": {
        "tag": "Javascript autocomplete",
        "code": "let egItems = [{\n        \"name\": \"Classic Whip SPF 30\",\n        \"link\": \"https://www.vacation.inc/products/sun-screen\",\n        \"keyWord\": `Classic Whip SPF 30 “The World’s Best-Smelling Sunscreen” SPF 30 Sunscreen Lotion — $18 Classic Lotion | The Worlds Best-Smelling Sunscreen | Vacation®`\n    },\n    {\n        \"name\": \"Ball Boy Scented Candle\",\n        \"link\": \"https://www.vacation.inc/products/ball-boy-candle\",\n        \"keyWord\": `Ball Boy Scented Candle Prince® x Vacation® Collection — $42 Vacation® X Prince® |  Ball Boy Scented Candle`\n    },\n    {\n        \"name\": \"Chardonnay Oil SPF 30\",\n        \"link\": \"https://www.vacation.inc/products/chardonnay-oil-spf-30\",\n        \"keyWord\": `Chardonnay Oil SPF 30 Chardonnay Oil | SPF 30 Sunscreen Oil | Vacation® “The World's Most Indulgent Sunscreen” SPF 30 Sunscreen Oil — $22`\n    },\n    {\n        \"name\": \"Classic Spray SPF 30\",\n        \"link\": \"https://www.vacation.inc/products/classic-whip-spf-30\",\n        \"keyWord\": `Classic Spray SPF 30 Vacation® Classic Whip |  SPF 30 Sunscreen Mousse “Dessert For Your Skin” SPF 30 Sunscreen Mousse — $22`\n    },\n    {\n        \"name\": \"Super Spritzer\",\n        \"link\": \"https://www.vacation.inc/products/super-spritzer\",\n        \"keyWord\": `Super Spritzer “Vaporized Refreshment” Hydrating Face Mist — $12 Super Spritzer | The Worlds Best-Smelling Sunscreen | Vacation®`\n    },\n    {\n        \"name\": \"Mineral Lotion SPF 30\",\n        \"link\": \"https://www.vacation.inc/products/mineral-lotion-spf-30\",\n        \"keyWord\": `Mineral Lotion SPF 30 “Luxury-Grade Zinc Based Protection” SPF 30 Mineral Lotion — $20 Mineral Lotion | The Worlds Best-Smelling Sunscreen | Vacation®`\n    }\n]\n\nfunction showList() {\n    document.querySelector(\"#egSearch\").addEventListener(\"input\", function () {\n        let query = this.value.toUpperCase();\n        let egShowItemsHtml = '';\n        egItems.forEach(item => {\n            if ((query !== \"\") && (matchQuery(item.keyWord, query))) {\n                egShowItemsHtml += ` <li class=\"eg-item\"><a href = '${item.link}' class=\"eg-product-name\">${item.name}</a></li>`;\n            }\n        });\n        document.querySelector(\".eg-suggestion-list\").innerHTML = '';\n        document.querySelector(\".eg-suggestion-list\").insertAdjacentHTML(\"beforeend\", egShowItemsHtml);\n    });\n}",
        "desc": " This code defines an array of objects that contain information about various products, including a name, link, and a keyword that describes the product. It also includes a function called showList() which listens for user input in a search box and filters the products based on whether their associated keyword matches the search query. It then dynamically generates HTML elements to display a list of the filtered products as clickable links.\nThis code adds an event listener to an input field that filters through an array of products and displays matching items in a suggestion list. The suggestion list is updated dynamically as the user types into the input field."
    },
    "This JavaScript function matches a query string to a mapping string by removing special characters and consecutive spaces, converting both strings to uppercase, and checking if the query string is present in the mapping string. It returns a Boolean value indicating whether the match was successful or not.This code defines a function matchQuery that takes in two parameters: keyWord and query. The function first removes any non-alphanumeric characters and extra spaces from both the keyWord and query strings using regular expressions, then converts them to upper case. Finally, it checks if the query string appears in the modified keyWord string, and returns true if it does and false otherwise. Essentially, this function checks if a search query matches a given keyword by removing special characters, extra spaces, and case sensitivity.": {
        "tag": "This JavaScript function matches a query string to a mapping string by removing special characters and consecutive spaces, converting both strings to uppercase, and checking if the query string is present in the mapping string. It returns a Boolean value indicating whether the match was successful or not.",
        "code": "function matchQuery(keyWord, query) {\n    return (keyWord.replace(/[^\\w\\s]/gi, '').replace(/\\s+/g, ' ').toUpperCase().indexOf(query.replace(/[^\\w\\s]/gi, '').replace(/\\s+/g, ' ').toUpperCase()) != -1);\n}",
        "desc": "This code defines a function matchQuery that takes in two parameters: keyWord and query. The function first removes any non-alphanumeric characters and extra spaces from both the keyWord and query strings using regular expressions, then converts them to upper case. Finally, it checks if the query string appears in the modified keyWord string, and returns true if it does and false otherwise. Essentially, this function checks if a search query matches a given keyword by removing special characters, extra spaces, and case sensitivity."
    },
    "DETECT FETCH APIThis code detects when the Fetch API is used and modifies its behavior. Specifically, it sets a timeout and executes some functions when a specific URL is requested.\nThis code overrides the default fetch function in the browser to check if an AJAX call is made to a specific URL (/GetProducts). If such a call is made, it sets a timeout function to run after 2 seconds which then checks if the current web page has a specific CSS class (\"eg-list-view\"). If the class is present, it calls the moveCta() and getData() functions. Finally, it returns the original fetch function to its default behavior.": {
        "tag": "DETECT FETCH API",
        "code": "function checkAjax() {\n    const originalFetch = window.fetch;\n    window.fetch = function (input, init) {\n        if (input.url) {\n            if (input.url.indexOf('/GetProducts') !== -1) {\n                setTimeout(() => {\n                    if (document.body.classList.contains(\"eg-list-view\")) {\n                        moveCta();\n                    }\n                    getData();\n                }, 2000);\n            }\n        }\n        return originalFetch(input, init);\n    };\n}",
        "desc": "This code detects when the Fetch API is used and modifies its behavior. Specifically, it sets a timeout and executes some functions when a specific URL is requested.\nThis code overrides the default fetch function in the browser to check if an AJAX call is made to a specific URL (/GetProducts). If such a call is made, it sets a timeout function to run after 2 seconds which then checks if the current web page has a specific CSS class (\"eg-list-view\"). If the class is present, it calls the moveCta() and getData() functions. Finally, it returns the original fetch function to its default behavior."
    },
    "Make multiple requests without waiting.This code fetches product description data for each product on a webpage using AJAX and displays the data alongside the product price.\n\nThe first block of code uses querySelectorAll to select all the product card elements on the page and checks if each one already has a .eg-para element. If not, it extracts the product URL and calls the getPDPData function with that URL.\n\nThe getPDPData function makes an AJAX request to the URL provided and retrieves the HTML response data. It then creates a temporary element (<div>) and sets the HTML response data as its content. It then extracts the product description text from the element and checks if the description element exists. If the description element exists, it selects the corresponding product card on the page and inserts the description text before the product price element. If the description element does not exist, it recursively calls the getPDPData function with the same URL until it retrieves the correct data.": {
        "tag": "Make multiple requests without waiting.",
        "code": "document.querySelectorAll(\"html body #coveo-product-list .c-c-pl_products .c-c-pl_results_container .c-c-pl_results_list .c-c-product-card\").forEach(item => {\n    if (!item.querySelector(\".eg-para\")) {\n        let url = item.querySelector(\".c-c-product-card_img-wrapper\") && item.querySelector(\".c-c-product-card_img-wrapper\").href;\n        getPDPData(url);\n    }\n});\n\nfunction getPDPData(url) {\n    var xhttp = new XMLHttpRequest();\n    xhttp.onreadystatechange = function () {\n        if (this.readyState == 4 && this.status == 200) {\n            var data = this.responseText;\n            // console.log(this.responseURL, document.querySelector('li.c-c-product-card a[href=\"' + this.responseURL + '\"]'));\n            var ele = document.createElement(\"div\");\n            ele.innerHTML = data;\n            var egDesEle = ele.querySelector(\".c-product-description\");\n            // checking if element exists or not\n            if (egDesEle) {\n                let egItem = document.querySelector('li.c-c-product-card a[href=\"' + this.responseURL + '\"]').closest('li.c-c-product-card');\n                if (!egItem.querySelector(\".eg-para\")) {\n                    egItem.querySelector(\".c-c-product-card_price\").insertAdjacentHTML(\"beforebegin\", `<p class=\"eg-para\">${egDesEle.innerText}</p>`);\n                }\n            } /*else {\n                getPDPData(url);\n            }*/\n        }\n    };\n    xhttp.open(\"GET\", url, true);\n    xhttp.send();\n}",
        "desc": "This code fetches product description data for each product on a webpage using AJAX and displays the data alongside the product price.\n\nThe first block of code uses querySelectorAll to select all the product card elements on the page and checks if each one already has a .eg-para element. If not, it extracts the product URL and calls the getPDPData function with that URL.\n\nThe getPDPData function makes an AJAX request to the URL provided and retrieves the HTML response data. It then creates a temporary element (<div>) and sets the HTML response data as its content. It then extracts the product description text from the element and checks if the description element exists. If the description element exists, it selects the corresponding product card on the page and inserts the description text before the product price element. If the description element does not exist, it recursively calls the getPDPData function with the same URL until it retrieves the correct data."
    },
    "BEST WAY TO DO TASK WHEN PAGE SCROLLThis code listens for the \"scroll\" event on the window object and adds an event listener function to it. The function does the following:\n\nIt retrieves the current vertical scroll position using window.pageYOffset or document.documentElement.scrollTop.\n\nIt checks if the current scroll position is less than the last scroll position stored in lastScrollTop. If it is, it adds the class \"filter-nav_fixed\" to the element with class \"filter-nav\" using classList.add().\n\nIf the current scroll position is greater than lastScrollTop, it removes the class \"filter-nav_fixed\" using classList.remove().\n\nFinally, lastScrollTop is updated to be either 0 or the current scroll position, depending on whether the scroll position is non-positive or positive, respectively.\n\nThe result of this code is that whenever the user scrolls the page, the class \"filter-nav_fixed\" is added or removed from the \"filter-nav\" element depending on the direction of the scroll. This allows for the implementation of a fixed header effect, where the header remains fixed at the top of the screen when the user scrolls down the page.": {
        "tag": "BEST WAY TO DO TASK WHEN PAGE SCROLL",
        "code": "let lastScrollTop = 0;\nwindow.addEventListener(\"scroll\", function () {\n    var st = window.pageYOffset || document.documentElement.scrollTop;\n    if (st < lastScrollTop) {\n        document.querySelector(\".filter-nav\").classList.add(\"filter-nav_fixed\");\n    } else if (st > lastScrollTop) {\n        document.querySelector(\".filter-nav\").classList.remove(\"filter-nav_fixed\");\n    }\n\n    lastScrollTop = st <= 0 ? 0 : st; // For Mobile or negative scrolling\n}, false);",
        "desc": "This code listens for the \"scroll\" event on the window object and adds an event listener function to it. The function does the following:\n\nIt retrieves the current vertical scroll position using window.pageYOffset or document.documentElement.scrollTop.\n\nIt checks if the current scroll position is less than the last scroll position stored in lastScrollTop. If it is, it adds the class \"filter-nav_fixed\" to the element with class \"filter-nav\" using classList.add().\n\nIf the current scroll position is greater than lastScrollTop, it removes the class \"filter-nav_fixed\" using classList.remove().\n\nFinally, lastScrollTop is updated to be either 0 or the current scroll position, depending on whether the scroll position is non-positive or positive, respectively.\n\nThe result of this code is that whenever the user scrolls the page, the class \"filter-nav_fixed\" is added or removed from the \"filter-nav\" element depending on the direction of the scroll. This allows for the implementation of a fixed header effect, where the header remains fixed at the top of the screen when the user scrolls down the page."
    },
    "DETECT OUTSIDE CLICK OF AN ELEMENTThis function detects clicks outside of a specified element by attaching a mousedown event listener to the body of the document. If the event target is not the specified element or one of its children, it means that the click occurred outside of the element, and the function removes a specified class from the element and from the body of the document. This is useful for closing popups or modals when a user clicks outside of them.": {
        "tag": "DETECT OUTSIDE CLICK OF AN ELEMENT",
        "code": "function detectClickOutside(element) {\n    // Attach a click event listener to a parent element that exists in the DOM\n    document.body.addEventListener('mousedown', function (event) {\n        // Check if the event target is the element or one of its children\n        if (event.target !== element && !element.contains(event.target)) {\n            // The click occurred outside of the element, do something...\n            // console.log('Clicked outside of the element!');\n            document.querySelector(\".eg-popuped\") && document.querySelector(\".eg-popuped\").classList.remove(\"eg-popuped\");\n            document.body.classList.remove(\"eg-popup\");\n        }\n    });\n}",
        "desc": "This function detects clicks outside of a specified element by attaching a mousedown event listener to the body of the document. If the event target is not the specified element or one of its children, it means that the click occurred outside of the element, and the function removes a specified class from the element and from the body of the document. This is useful for closing popups or modals when a user clicks outside of them."
    },
    "MUTATION OBSERVER BASIC SNIPPETMUTATION OBSERVER BASIC SNIPPET": {
        "tag": "MUTATION OBSERVER BASIC SNIPPET",
        "code": "// Select the node that will be observed for mutations\nconst targetNode = document.body;\n\n// Options for the observer (which mutations to observe)\nconst config = {\n    attributes: true,\n    childList: true,\n    subtree: true\n};\n\n// Callback function to execute when mutations are observed\nconst callback = function (mutationsList, observer) {\n    for (const mutation of mutationsList) {\n        if (mutation.type === 'childList') {\n            console.log('A child node has been added or removed.');\n        } else if (mutation.type === 'attributes') {\n            console.log('The ' + mutation.attributeName + ' attribute was modified.');\n        }\n    }\n};\n\n// Create an observer instance linked to the callback function\nconst observer = new MutationObserver(callback);\n\n// Start observing the target node for configured mutations\nobserver.observe(targetNode, config);",
        "desc": "MUTATION OBSERVER BASIC SNIPPET"
    },
    "Download json object data as fileThis code defines a function called download that takes in data, filename, and type as parameters and downloads the data as a file.\n/*\nThis code defines a function called download that takes three parameters: data, filename, and type. It creates a new Blob object using the data and type parameters and then checks if the browser is Internet Explorer 10 or above. If it is, it uses the msSaveOrOpenBlob method to download the file. Otherwise, it creates a new a element and sets its href attribute to a URL created using URL.createObjectURL(). It sets the download attribute to the filename parameter and appends the a element to the document body. Finally, it simulates a click on the a element to download the file and removes the a element and the URL object after the download is complete.\n\nTo use this function, you can call it with the data you want to download as the first parameter, the desired filename as the second parameter, and the file type as the third parameter. For example, download(JSON.stringify(egLogos), 'filename', 'filetype'); would download the data in the egLogos variable as a file with the name filename and the specified file type.": {
        "tag": "Download json object data as file",
        "code": "function download(data, filename, type) {\n    var file = new Blob([data], {\n        type: type\n    });\n    if (window.navigator.msSaveOrOpenBlob) // IE10+\n        window.navigator.msSaveOrOpenBlob(file, filename);\n    else { // Others\n        var a = document.createElement(\"a\"),\n            url = URL.createObjectURL(file);\n        a.href = url;\n        a.download = filename;\n        document.body.appendChild(a);\n        a.click();\n        setTimeout(function () {\n            document.body.removeChild(a);\n            window.URL.revokeObjectURL(url);\n        }, 0);\n    }\n}\ndownload(JSON.stringify(egLogos), 'filename', 'filetype');",
        "desc": "This code defines a function called download that takes in data, filename, and type as parameters and downloads the data as a file.\n/*\nThis code defines a function called download that takes three parameters: data, filename, and type. It creates a new Blob object using the data and type parameters and then checks if the browser is Internet Explorer 10 or above. If it is, it uses the msSaveOrOpenBlob method to download the file. Otherwise, it creates a new a element and sets its href attribute to a URL created using URL.createObjectURL(). It sets the download attribute to the filename parameter and appends the a element to the document body. Finally, it simulates a click on the a element to download the file and removes the a element and the URL object after the download is complete.\n\nTo use this function, you can call it with the data you want to download as the first parameter, the desired filename as the second parameter, and the file type as the third parameter. For example, download(JSON.stringify(egLogos), 'filename', 'filetype'); would download the data in the egLogos variable as a file with the name filename and the specified file type."
    },
    "Check for broken linksThis code defines an asynchronous function checkLinks that accepts an object of links as its argument. The function iterates through the links and uses the fetch() method to check if each link is valid or not. The result is an object that contains the links and their status (true for valid, false for broken). The function returns this object as a Promise.": {
        "tag": "Check for broken links",
        "code": "async function checkLinks(json) {\n    let result = {};\n    for (const [key, value] of Object.entries(json)) {\n        try {\n            const response = await fetch(value);\n            // result[key] = response.ok;\n        } catch (error) {\n            result[key] = value;\n        }\n    }\n    return result;\n}\n\nconst json = {\n    \"ABB\": \"https://octostatic.com/nextopart/static/manufacturer-logos/ABB.png\",\n    \"Amphenol\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Amphenol.png\",\n    \"Analog Services\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Analog%20Services.png\",\n    \"Biostar\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Biostar.png\",\n    \"Bose\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Bose.png\",\n    \"Bourns\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Bourns%20.png\",\n    \"Briggs Stratton\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Briggs%20Stratton%20.png\"\n};\n\ncheckLinks(json).then(result => console.log(result));",
        "desc": "This code defines an asynchronous function checkLinks that accepts an object of links as its argument. The function iterates through the links and uses the fetch() method to check if each link is valid or not. The result is an object that contains the links and their status (true for valid, false for broken). The function returns this object as a Promise."
    },
    "A function that takes a name and returns the value of the corresponding key from an object if any key contains the name.This code defines a function called findByName that takes a string argument and returns the corresponding value from the names object if the key contains the specified name. The names object contains key-value pairs, where the key is a string and the value is a URL to an image. The function uses a for loop to iterate over the keys of the names object and checks if the key contains the specified name using the includes() method. If a match is found, the function returns the corresponding value, otherwise it returns null. The console.log() statements demonstrate the usage of the function with sample input values.": {
        "tag": "A function that takes a name and returns the value of the corresponding key from an object if any key contains the name.",
        "code": "function findByName(name) {\n    for (const [key, value] of Object.entries(names)) {\n        if (key.toLowerCase().includes(name.toLowerCase())) {\n            return value;\n        }\n    }\n    return null;\n}\n\n\nconst names = {\n    \"ABB\": \"https://octostatic.com/nextopart/static/manufacturer-logos/ABB.png\",\n    \"Amphenol\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Amphenol.png\",\n    \"Analog Services\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Analog%20Services.png\",\n    \"Biostar\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Biostar.png\",\n    \"Bose\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Bose.png\",\n    \"Bourns\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Bourns%20.png\",\n    \"Briggs Stratton\": \"https://octostatic.com/nextopart/static/manufacturer-logos/Briggs%20Stratton%20.png\"\n};\n\nconsole.log(findByName(\"Brigss\")); // \"https://octostatic.com/nextopart/static/manufacturer-logos/Briggs%20Stratton%20.png\"\nconsole.log(findByName(\"Analog\")); // \"https://octostatic.com/nextopart/static/manufacturer-logos/Analog%20Services.png\"\nconsole.log(findByName(\"Samsung\")); // null",
        "desc": "This code defines a function called findByName that takes a string argument and returns the corresponding value from the names object if the key contains the specified name. The names object contains key-value pairs, where the key is a string and the value is a URL to an image. The function uses a for loop to iterate over the keys of the names object and checks if the key contains the specified name using the includes() method. If a match is found, the function returns the corresponding value, otherwise it returns null. The console.log() statements demonstrate the usage of the function with sample input values."
    }
}

let id = 0;
for (const key in data) {
    if (data.hasOwnProperty(key)) {
        let heading = data[key].tag;
        let code = data[key].code;
        let desc = data[key].desc;
        document.querySelector(".codes-list").insertAdjacentHTML("beforeend", `<li class="codes-list-item" id="code-snippet-${id}"><h2 class="tagline"></h2><code class="code"></code><pre class="desc"></pre></li>`);
        document.querySelector(`#code-snippet-${id} .tagline`).innerText = heading;
        document.querySelector(`#code-snippet-${id} .code`).innerText = code;
        document.querySelector(`#code-snippet-${id} .desc`).innerText = desc;
        document.querySelector(`#code-snippet-${id} .desc`).setAttribute("data-tag", key);
        id += 1;
    }
}

addCopyToClick();

document.querySelector(".search-group").addEventListener("submit", (e) => {
    e.preventDefault();
});

document.querySelector(".search-box").addEventListener("input", function () {
    let query = this.value;
    filter(query)
});

function filter(query) {
    document.querySelectorAll(".desc").forEach(desc => {
        if (desc.getAttribute("data-tag").toUpperCase().indexOf(query.toUpperCase()) == -1) {
            desc.parentElement.classList.add("hide-it");
        } else {
            desc.parentElement.classList.remove("hide-it");
            if (query.trim() !== "") {
                desc.parentElement.classList.add("filter-match");
            } else {
                desc.parentElement.classList.remove("filter-match");
            }
        }
    });
}

function addCopyToClick() {
    document.querySelectorAll(".code").forEach(code => {
        code.addEventListener("click", function () {
            const el = document.createElement('textarea');
            el.value = this.innerText;
            document.body.appendChild(el);
            el.select();
            document.execCommand('copy');
            this.style.cssText = `--code-text:"copied"`;
            setTimeout(()=>{
                this.style.cssText = `--code-text:"copy"`;
            },3000);
            document.body.removeChild(el);
        });
    });
}

function goToTop(){
    window.scrollTo({
        top:0,
        behavior:"smooth",
        left:0
    });
}